[project]
name = "dotfiles"
version = "1.4.0"
dependencies = [
    "ansible-lint",
    "ansible",
    "jmespath",
    "vim-vint",
    "yamllint",
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
