[project]
requires-python = ">=3.14"
name = "dotfiles"
version = "1.6.4"
dependencies = [
    "ansible-lint",
    "ansible",
    "mitogen",
    "jmespath"
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
