name: ansible

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ansible_lint:
    name: ansible_lint
    uses: tenhishadow/github_actions_templates/.github/workflows/taskfile.uv.yaml@main
    with:
      os: ubuntu-latest
      task_target: lint

  ansible_exec:
    name: ansible_exec (${{ matrix.os }})
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    uses: tenhishadow/github_actions_templates/.github/workflows/taskfile.uv.yaml@main
    with:
      os: ${{ matrix.os }}
      task_target: default

